import { METRICS } from '../../telemetry/src/metrics.js';
import { DASHBOARD, type Match, type Query, type Selector } from './definitions.js';
import type { ResolvedAlert } from './thresholds.js';

/**
 * Renderers for the operations definitions (ADR 0039). The definitions are the source; each
 * output is generated from them and checked in, so a reviewer sees exactly what will alert.
 *
 * - `operations.json`: the provider-neutral form, for any backend (OTLP-native ones included).
 * - `prometheus-rules.yaml`: alerting rules for Prometheus-compatible systems scraping
 *   `/metrics` or receiving OTLP metrics with the same names.
 * - `grafana-dashboard.json`: a dashboard over the same queries.
 */

const quote = (value: string) => JSON.stringify(value);
const escapeRegex = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function matcher(label: string, match: Match): string {
  if (typeof match === 'string') return `${label}=${quote(match)}`;
  if ('not' in match) return `${label}!=${quote(match.not)}`;
  if ('in' in match) return `${label}=~${quote(match.in.map(escapeRegex).join('|'))}`;
  return `${label}!~${quote(match.notIn.map(escapeRegex).join('|'))}`;
}

function selector(where: Selector | undefined): string {
  const parts = Object.entries(where ?? {}).map(([label, match]) => matcher(label, match));
  return parts.length ? `{${parts.join(',')}}` : '';
}

const sumBy = (by: readonly string[] | undefined, extra: string[] = []) => {
  const labels = [...(by ?? []), ...extra];
  return labels.length ? `sum by (${labels.join(', ')})` : 'sum';
};

/** PromQL for a neutral query. */
export function promql(query: Query): string {
  switch (query.kind) {
    case 'value':
      return `${sumBy(query.by)} (${query.metric}${selector(query.where)})`;
    case 'increase': {
      const series =
        METRICS[query.metric].type === 'histogram' ? `${query.metric}_count` : query.metric;
      return `${sumBy(query.by)} (increase(${series}${selector(query.where)}[${query.window}]))`;
    }
    case 'quantile':
      return `histogram_quantile(${query.quantile}, ${sumBy(query.by, ['le'])} (rate(${query.metric}_bucket${selector(query.where)}[${query.window}])))`;
    case 'ratio':
      return `(${promql(query.numerator)}) / (${promql(query.denominator)})`;
  }
}

const ruleName = (id: string) =>
  `Af${id
    .split('-')
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join('')}`;

const yamlString = (value: string) => JSON.stringify(value);

export function prometheusRules(alerts: readonly ResolvedAlert[]): string {
  const lines = [
    '# Generated by `npm run ops:render` from packages/operations (ADR 0039). Do not edit:',
    '# change alert-thresholds.json for the deployment and render again.',
    'groups:',
    '  - name: agents-foundry-pilot',
    '    rules:',
  ];
  for (const alert of alerts) {
    if (!alert.enabled) continue;
    lines.push(
      `      - alert: ${ruleName(alert.id)}`,
      `        expr: ${yamlString(`${promql(alert.query)} ${alert.comparison} ${alert.threshold}`)}`,
      `        for: ${alert.for}`,
      '        labels:',
      `          severity: ${alert.severity}`,
      `          af_alert: ${alert.id}`,
      '        annotations:',
      `          summary: ${yamlString(alert.title)}`,
      `          description: ${yamlString(alert.description)}`,
      `          runbook: ${yamlString(`docs/pilot-runbook.md#${alert.runbook}`)}`,
    );
  }
  return `${lines.join('\n')}\n`;
}

const UNITS = { count: 'short', ratio: 'percentunit', ms: 'ms', tokens: 'short', micros: 'short' };

export function grafanaDashboard(): object {
  let id = 0;
  let y = 0;
  const panels: object[] = [];
  for (const section of DASHBOARD) {
    panels.push({
      id: ++id,
      type: 'row',
      title: section.title,
      collapsed: false,
      gridPos: { h: 1, w: 24, x: 0, y: y++ },
      panels: [],
    });
    section.panels.forEach((panel, index) => {
      const stat = panel.query.kind === 'value' || panel.query.kind === 'ratio';
      panels.push({
        id: ++id,
        type: stat ? 'stat' : 'timeseries',
        title: panel.title,
        description: panel.description,
        datasource: { type: 'prometheus', uid: '${datasource}' },
        fieldConfig: { defaults: { unit: UNITS[panel.unit] }, overrides: [] },
        gridPos: { h: 7, w: 8, x: (index % 3) * 8, y: y + Math.floor(index / 3) * 7 },
        targets: [{ refId: 'A', expr: promql(panel.query), legendFormat: '__auto' }],
      });
    });
    y += Math.ceil(section.panels.length / 3) * 7;
  }
  return {
    title: 'Agents Foundry pilot',
    uid: 'agents-foundry-pilot',
    description: 'Generated by `npm run ops:render` from packages/operations (ADR 0039).',
    tags: ['agents-foundry'],
    timezone: 'utc',
    schemaVersion: 39,
    time: { from: 'now-6h', to: 'now' },
    templating: {
      list: [{ name: 'datasource', type: 'datasource', query: 'prometheus', label: 'Data source' }],
    },
    panels,
  };
}

export function neutralDefinitions(alerts: readonly ResolvedAlert[]): object {
  return {
    description:
      'Agents Foundry operator dashboards and alerts (ADR 0039). Queries name metrics of the platform catalog; render them for your monitoring system.',
    dashboard: DASHBOARD,
    alerts: alerts.map(({ overridden: _overridden, ...alert }) => alert),
  };
}
